name: Setup
description: Setup Node Env

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v4
      with:
        path: ${{ env.NPM_CACHE }}
        key: ${{ runner.os }}-npm-cache-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-cache-

    - name: Install dependencies
      run: npm ci
      shell: bash
